### PR TITLE
Publication cleanup

### PR DESCRIPTION
**Pull request by felicitas215**
:-)

### CODE REVIEW

**Comment by felicitas215** [comment]
The second to last commit fixes a critical bug when using Helixer.py with `--no-overlap`, `--overlap-offset=None` (default) and `--overlap-core-length=None` (default).

**Comment by alisandra** [comment]
Thanks!

As this is a lot, is there anything I should put a more careful eye on that we haven't previously discussed?

Also, as there are functional changes, could you directly increment the version number so we can give it a tag and a docker image too?

**Comment by felicitas215** [comment]
The only thing, that we didn't discuss was the bug fix. I only noticed it today. I tested Helixer.py now with and without overlap, so everything should be fine. But maybe you can take a look at it (in case I missed something). The rest is just documentation and giving the user control over `write-by`  during fasta conversion. (And maybe if you like the new README :-))

**Comment by alisandra** [comment]
all merged, looks great, thanks for this!! :fire:

**Pull request merged**
